---
version: "2.0"

services:
  web:
    image: slowriot/gitpages_jekyll_akash
    expose:
      - port: 80
        proto: tcp
        to:
          - global: true
    env:
      - PUBLISH_REPO="https://github.com/daattali/beautiful-jekyll.git"
      - PUBLISH_BRANCH="gh-pages"
      - PUBLISH_PATH="/"

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
