---
version: "2.0"

services:
  web:
    image: slowriot/anubis
    expose:
      - port: 80
        to:
          - global: true
    env:
      - PUBLISH_REPO=https://github.com/daattali/beautiful-jekyll.git
      - PUBLISH_BRANCH=gh-pages
      - PUBLISH_PATH=/
      - RADICLE_SEEDS=hyncrnppok8iam6y5oemg4fkumj86mc4wsdiirp83z7tdxchk5dbn6@seed.upstream.radicle.xyz:8776
      - REFRESH_DELAY=30

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
